Algoritmo "CalculoDaArea"
// Disciplina   : Lógica de Programação VisualG
// Professor   : Jailson
// Descrição   : Program que faz o calculo da área do circulo.
// Autor(a)    : Breno
// Data atual  : 20/03/2026
  Var
   raio: real
   area: real


Inicio
   escreva("Digite o número do raio do circulo: ")
   leia(raio)
   
   area<- pi * raio ^ 2

   escreval("Resultado da area do circulo: " ,area)


Fimalgoritmo