Algoritmo "MaiorQue100"
// Disciplina   : linguagem de programação com o Visual G
// Professor   : Jailson
// Descrição   : Verifica número positivo maior que 100
// Autor(a)    : Breno B.
// Data atual  : 20/04/2026

Var
   n: inteiro

Inicio
Escreval("Digite numero")
   leia(n)

   se n > 100 entao
      escreva("Maior que 100")
   senao
      escreva("Menor ou igual")
   fimse
Fimalgoritmo