Algoritmo "Media de aluno"
// Disciplina   : Lógica de Programação VisualG
// Professor   : Jailson
// Descrição   : faz a meido das notas/ numeros inseridos
// Autor(a)    : Breno
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis
nota1:real
 nota2:real
 nota3:real
 media:real
 resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("insira sua primeira nota")
leia (nota1)
escreva("insira sua segunda nota")
leia (nota2)
escreva("insira sua terceira nota")
leia (nota3)
resultado<- nota1 + nota2 + nota3

media<- resultado /3

escreval("Nota do aluno: " ,media )


Fimalgoritmo