Algoritmo "ConsumoCombustivel"
// Disciplina   : linguagem de programação com o Visual G
// Professor   : Jailson
// Descrição   : Calcula consumo médio
// Autor(a)    : Breno B.
// Data atual  : 20/04/2026

Var
   distancia,litros,consumo: real

Inicio
   escreval("Digite distancia e litros:")
   leia(distancia,litros)

   consumo <- distancia / litros

   escreva(consumo)
Fimalgoritmo