Algoritmo "ControleCommits"
// Disciplina   : linguagem de programação com o Visual G
// Professor   : Jailson
// Descrição   : Verifica atividade no GitHub
// Autor(a)    : Breno B.
// Data atual  : 20/04/2026

Var
   commits: inteiro

Inicio
   escreval("Digite quantidade de commits:")
   leia(commits)

   se commits > 0 entao
      escreva("Repositorio atualizado")
   fimse
Fimalgoritmo