Algoritmo "ConverterMestrosParaCentimetors"
// Disciplina   : Lógica de Programação VisualG
// Professor   : Jailson
// Descrição   : Programa que converte metros para centimetros
// Autor(a)    : Breno
// Data atual  : 29/03/2026
Var
// Seção de Declarações das variáveis 
metros: real
cm: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Convertendo metros para centímetros")
escreval("Quantos mestros você quer coverter para centímetros?")
leia (metros)
cm<- metros * 100
escreval(metros," Metros são ",cm, " Centímetros!")

Fimalgoritmo