Algoritmo "IntervaloNumero"
// Disciplina   : linguagem de programação com o Visual G
// Professor   : Jailson
// Descrição   : Verifica se número está entre 10 e 20
// Autor(a)    : Breno B.
// Data atual  : 20/04/2026

Var
   n: inteiro

Inicio
   Escreval("Digite numero")
   leia(n)

   se n >= 10 e n <= 20 entao
      escreva("Dentro do intervalo")
   senao
      escreva("Fora do intervalo")
   fimse
Fimalgoritmo